#!/usr/bin/env python3
"""Create a local editable-dependency runner without modifying project metadata."""

import os
import shutil
import subprocess
import sys
from pathlib import Path

REPOSITORIES = {
    "activitysim": "https://github.com/activitySim/activitysim.git",
    "sharrow": "https://github.com/activitySim/sharrow.git",
}
MARKER = "# Generated by scripts/make-developer-env.py; local-only runner."
RUNNER = '''#!/usr/bin/env python3
# Generated by scripts/make-developer-env.py; local-only runner.
"""Run a command with the sibling ActivitySim and Sharrow source checkouts."""

import os
from pathlib import Path
import shutil
import subprocess
import sys


def main():
    root = Path(__file__).resolve().parent
    if len(sys.argv) < 2:
        print("Usage: python uv-local COMMAND [ARGUMENTS...]", file=sys.stderr)
        return 2
    uv = shutil.which("uv")
    if uv is None:
        print("uv is required on PATH; install it before running uv-local.", file=sys.stderr)
        return 1
    sources = [root.parent / name for name in ("activitysim", "sharrow")]
    for source in sources:
        if not (source / "pyproject.toml").is_file() or not (source / source.name).is_dir():
            print(f"Missing or unsupported sibling checkout: {source}", file=sys.stderr)
            return 1
    env = os.environ.copy()
    # These projects have flat layouts. Explicit source paths prevent setuptools'
    # editable finder from losing to released packages in uv's base environment.
    paths = [str(source) for source in sources]
    if env.get("PYTHONPATH"):
        paths.append(env["PYTHONPATH"])
    env["PYTHONPATH"] = os.pathsep.join(paths)
    command = [uv, "run", "--locked"]
    for source in sources:
        command.extend(["--with-editable", str(source)])
    command.extend(["--", *sys.argv[1:]])
    return subprocess.call(command, cwd=root, env=env)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except OSError as error:
        print(f"uv-local: {error}", file=sys.stderr)
        sys.exit(1)
'''


def git(root, *args):
    return subprocess.check_output(
        ["git", "-C", str(root), *args], text=True, stderr=subprocess.PIPE
    ).strip()


def validate_checkout(path):
    if not path.is_dir() or not (path / "pyproject.toml").is_file():
        raise ValueError(f"Existing sibling is not a Python checkout: {path}")
    if Path(git(path, "rev-parse", "--show-toplevel")).resolve() != path.resolve():
        raise ValueError(f"Sibling must be its own Git checkout: {path}")
    if not (path / path.name).is_dir():
        raise ValueError(f"Expected a flat package layout in {path}")


def setup(root):
    root = root.resolve()
    if Path(git(root, "rev-parse", "--show-toplevel")).resolve() != root:
        raise ValueError(
            "Run the script from a Lighthouse checkout, not an exported copy."
        )
    if not (root / "pyproject.toml").is_file() or not (root / "uv.lock").is_file():
        raise ValueError("Lighthouse pyproject.toml and uv.lock are required.")
    runner = root / "uv-local"
    if git(root, "ls-files", "--", "uv-local"):
        raise ValueError("uv-local is tracked; refusing to replace it.")
    if runner.is_symlink():
        raise ValueError("uv-local is a symlink; refusing to replace it.")
    if runner.exists():
        existing = runner.read_text(encoding="utf-8")
        legacy = existing.startswith("#!/bin/sh\n# Local-only runner:")
        if MARKER not in existing.splitlines() and not legacy:
            raise ValueError("uv-local already exists and is not a generated runner.")

    # Preflight every existing path before cloning or changing local files.
    for name in REPOSITORIES:
        sibling = root.parent / name
        if sibling.exists() or sibling.is_symlink():
            validate_checkout(sibling)
    for name, url in REPOSITORIES.items():
        sibling = root.parent / name
        if not sibling.exists():
            subprocess.run(["git", "clone", url, str(sibling)], check=True)
            validate_checkout(sibling)
            print(f"Cloned {name} into {sibling}")
        else:
            print(f"Keeping existing checkout: {sibling}")

    # Git resolves this correctly even when .git is a worktree pointer file.
    exclude = Path(git(root, "rev-parse", "--git-path", "info/exclude"))
    if not exclude.is_absolute():
        exclude = root / exclude
    exclude.parent.mkdir(parents=True, exist_ok=True)
    content = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    if "/uv-local" not in content.splitlines():
        with exclude.open("a", encoding="utf-8", newline="\n") as stream:
            if content and not content.endswith("\n"):
                stream.write("\n")
            stream.write("\n# Local editable dependency runner\n/uv-local\n")
    if not runner.exists() or runner.read_text(encoding="utf-8") != RUNNER:
        with runner.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(RUNNER)
    if os.name != "nt":
        runner.chmod(runner.stat().st_mode | 0o111)
    print(f"Ready: python {runner} COMMAND [ARGUMENTS...]")
    print(
        "Project metadata is unchanged. Dependencies install on the first runner invocation."
    )


def main():
    for tool in ("git", "uv"):
        if shutil.which(tool) is None:
            print(
                f"{tool} is required on PATH; install it and rerun setup.",
                file=sys.stderr,
            )
            return 1
    try:
        setup(Path(__file__).resolve().parents[1])
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        detail = getattr(error, "stderr", None) or str(error)
        print(f"Developer environment setup failed: {detail}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
